version: "3"
services:
        db:
                container_name: server.db
                image: mysql:8.0.22
                ports:
                        - 3306:3306
                environment:
                        MYSQL_DATABASE: fastStore
                        MYSQL_ROOT_PASSWORD: 131367Nhan
                volumes:
                        - ./data/mysql:/var/lib/mysql
        dbms:
                image: mcr.microsoft.com/mssql/server:2019-latest
                environment:
                        - ACCEPT_EULA=Y
                        - SA_PASSWORD=1234567Aa
                volumes:
                        - ./data:/data
                ports:
                        - 1433:1433
